### ISSUE TITLE
Whiteship consle machine broke

### ISSUE THREAD

**Issue by ADepressedPyroshark** [WaspStation/WaspStation-1.0#424]
Issue reported from  Round ID: [1559](https://scrubby.melonmesa.com/round/1559) (BoomerStation - MRP)

Reporting client version: 513.1528
I was just sending the whiteship somewhere and i get hit with this

TypeError: Unable to get property 'name' of undefined or null reference
   at i (http://127.0.0.1:58042/tmp11552/tgui.bundle.js:1:434921)
   at d (http://127.0.0.1:58042/tmp11552/tgui.bundle.js:1:435261)
   at Anonymous function (http://127.0.0.1:58042/tmp11552/tgui-common.chunk.js:1:223277)
   at Re (http://127.0.0.1:58042/tmp11552/tgui-common.chunk.js:1:223040)
   at Pe (http://127.0.0.1:58042/tmp11552/tgui-common.chunk.js:1:224080)
   at Anonymous function (http://127.0.0.1:58042/tmp11552/tgui-common.chunk.js:1:222540)
   at Re (http://127.0.0.1:58042/tmp11552/tgui-common.chunk.js:1:222079)
   at Pe (http://127.0.0.1:58042/tmp11552/tgui-common.chunk.js:1:224080)
   at Anonymous function (http://127.0.0.1:58042/tmp11552/tgui-common.chunk.js:1:222540)
   at Re (http://127.0.0.1:58042/tmp11552/tgui-common.chunk.js:1:222079)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)
State: {"ckey":"adepressedpyroshark","interface":"ShuttleConsole","window":{"key":"[0x2036e9a]-main","size":null,"fancy":1,"locked":1}}

All I think could have caused this was staying on the menu while the ship was moving  maaaarrg

EDIT:
The consle is still broke after i closed the manu and opened it. You can fix it by disconnecting the moniter then reconnecting it.

**Comment by MarkSuckerberg** [comment]
#420 testmerged, likely the cause
